# -*- coding: utf-8 -*-
"""partyhubs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zV-dtqJxdVgBrdH8CmjXI2XNYqRtNil-
"""

!pip install python-igraph
import igraph
import numpy as np
import pandas as pd
import scipy.stats
import matplotlib.pyplot as plt

!curl https://csx46.s3-us-west-2.amazonaws.com/han_hub_data.txt >han_hub_data.txt
hub_data = pd.read_csv("han_hub_data.txt", sep="\t", header=0).drop_duplicates()

hub_data.head()

hub_data.shape

!curl https://csx46.s3-us-west-2.amazonaws.com/han_network_edges.txt > han_network_edges.txt
edge_data = pd.read_csv("han_network_edges.txt", sep="\t", header=0)

edge_data.head()

edge_data.shape

inds = edge_data['PROTEINB'] > edge_data['PROTEINA']
temp = edge_data.loc[inds, ['PROTEINB', 'PROTEINA']]
edge_data.loc[inds, ['PROTEINA', 'PROTEINB']] = temp.values
edge_data = edge_data.drop_duplicates()
edge_data.shape

ppi_graph = igraph.Graph.TupleList(edge_data.values.tolist(), directed=False)
ppi_graph.summary()

ppi_graph.is_simple()

graph_vertices = ppi_graph.vs["name"]

graph_vertices[0:9]

graph_vertices_df = pd.DataFrame({'Protein': graph_vertices,'order': list(range(0, len(graph_vertices)))})
graph_vertices_df.head()

graph_vertices_df_merged = graph_vertices_df.merge(hub_data, how='outer', on="Protein")
graph_vertices_df_merged = graph_vertices_df_merged.sort_values("order")

graph_vertices_df_merged.head()

graph_vertices_df_merged.shape

vertex_types_np = np.array(graph_vertices_df_merged["HubType"].to_numpy().tolist())

vertex_types_np

date_hub_inds = np.where(vertex_types_np == "date")
party_hub_inds = np.where(vertex_types_np == "party")

ci_values = ppi_graph.transitivity_local_undirected()
ci_values_np = np.array(ci_values)

ci_values_np

ci_values_date_hubs = ci_values_np[date_hub_inds]
ci_values_party_hubs = ci_values_np[party_hub_inds]

plt.hist(ci_values_date_hubs, alpha=0.5, label="date")
plt.hist(ci_values_party_hubs, alpha=0.5, label="party")
plt.show()

scipy.stats.ks_2samp(ci_values_date_hubs, ci_values_party_hubs)