# -*- coding: utf-8 -*-
"""similarity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mQ2umMdWL-FMUQOTHmis_rnFx4mA5B4S
"""

!pip install python-igraph
import igraph
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.cluster.hierarchy
import scipy.spatial.distance

!curl https://csx46.s3-us-west-2.amazonaws.com/neph_gene_network.txt > neph_gene_network.txt

edge_list_neph = pd.read_csv("neph_gene_network.txt",
                              sep="\t",
                              names=["regulator","target"])

neph_graph = igraph.Graph.TupleList(edge_list_neph.values.tolist(), directed=False)
neph_graph.summary()

S = neph_graph.similarity_dice(loops=False)

D = 1 - np.matrix(S)
print(D.shape)

d = D.shape[0]
int(d*(d-1)/2)

vD = scipy.spatial.distance.squareform(D)
print(vD.shape)

hc = scipy.cluster.hierarchy.linkage(vD, method="average")
print(type(hc))
print(hc.shape)
print(pd.DataFrame(hc).head())

plt.figure()
fig = plt.gcf()
fig.set_size_inches(8, 8)
res = scipy.cluster.hierarchy.dendrogram(hc)
plt.show()

clusters = scipy.cluster.hierarchy.fcluster(hc, 0.65, 'distance')

print(type(clusters))
clusters.shape

len(np.unique(clusters))